CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS friendship_statuses (
    friendship_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER NOT NULL,
    CONSTRAINT fk_films_mpa
        FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,

    CONSTRAINT fk_film_genres_film
        FOREIGN KEY (film_id) REFERENCES films(film_id),

    CONSTRAINT fk_film_genres_genre
        FOREIGN KEY (genre_id) REFERENCES genres(genre_id),

    CONSTRAINT uq_film_genres
        UNIQUE (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,

    CONSTRAINT fk_film_likes_film
        FOREIGN KEY (film_id) REFERENCES films(film_id),

    CONSTRAINT fk_film_likes_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),

    CONSTRAINT uq_film_likes
        UNIQUE (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendships (
    friendship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id INTEGER NOT NULL,
    receiver_id INTEGER NOT NULL,
    friendship_status_id INTEGER NOT NULL,

    CONSTRAINT fk_friendships_requester
        FOREIGN KEY (requester_id) REFERENCES users(user_id),

    CONSTRAINT fk_friendships_receiver
        FOREIGN KEY (receiver_id) REFERENCES users(user_id),

    CONSTRAINT fk_friendships_status
        FOREIGN KEY (friendship_status_id)
            REFERENCES friendship_statuses(friendship_status_id),

    CONSTRAINT uq_friendships
        UNIQUE (requester_id, receiver_id)
);
